set_datetime:
  target:
    entity:
      domain: climate
      integration: eurotronic_cometblue
  fields:
    datetime:
      selector:
        datetime:

get_schedule:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: climate
              integration: eurotronic_cometblue

set_schedule:
  target:
    entity:
      domain: climate
      integration: eurotronic_cometblue
  fields:
    monday:
      example: |
        start1: 07:00:00
        end1: 09:00:00
        start2: 10:00:00
        end2: 12:00:00
        start3: 13:00:00
        end3: 17:00:00
        start4: 20:00:00
        end4: 23:00:00
      required: false
      selector:
        object:
    tuesday:
      example: |
        start1: 09:00:00
        end1: 12:00:00
        start2: 17:00:00
        end2: 19:00:00
      required: false
      selector:
        object:
    wednesday:
      example: |
        start1: 09:00:00
        end1: 12:00:00
        start2: 17:00:00
        end2: 19:00:00
      required: false
      selector:
        object:
    thursday:
      example: |
        start1: 09:00:00
        end1: 12:00:00
        start2: 17:00:00
        end2: 19:00:00
      required: false
      selector:
        object:
    friday:
      example: |
        {}
      required: false
      selector:
        object:
    saturday:
      example: |
        start1: 09:00:00
        end1: 12:00:00
        start2: 17:00:00
        end2: 19:00:00
      required: false
      selector:
        object:
    sunday:
      example: |
        start1: 09:00:00
        end1: 12:00:00
        start2: 17:00:00
        end2: 19:00:00
      required: false
      selector:
        object:

set_holiday:
  target:
    entity:
      domain: climate
      integration: eurotronic_cometblue
  fields:
    start:
      example: 2023-12-24
      required: true
      selector:
        datetime:
    end:
      example: 2023-12-31
      required: true
      selector:
        datetime:
    temperature:
      example: 20
      required: true
      selector:
        number:
          min: 8
          max: 28
          step: 0.5
          unit_of_measurement: °C
